CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS users(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
USERNAME CHAR(125),
FIRST_NAME CHAR(125),
LAST_NAME CHAR(125),
UNIQUE (TELEGRAM_ID)
)
"""

INSERT_USER_QUERY = """
INSERT INTO users VALUES (?, ?, ?, ?, ?)
"""


CREATE_ANSWER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS answers(
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
ANSWER CHAR(50),
FOREIGN KEY (TELEGRAM_ID) REFERENCES users(TELEGRAM_ID)
)
"""

INSERT_ANSWER_QUERY = """
INSERT INTO answers (TELEGRAM_ID, ANSWER) VALUES ( ?, ?)
"""